### ISSUE TITLE
Noms des stations mal écrits

### ISSUE THREAD

**Issue by elbuki** [pgrimaud/ratp-api-rest#11]
Bonjour monsieur, ce project est très très super, felicitations.

Est-ce que vous savez pourquoi les noms des stations de metro sont mal écrits? Comme ça: `La Defense / Chateau de Vincennes`.

C'est pour l'encoding utilisé dans RATP serveurs?

Pardon pour mon niveau du français et merci beaucoup!

**Comment by pgrimaud** [comment]
Bonjour @elbuki,
Ce middleware ne fait que transiter les informations de l'open data RATP.

Donc j'imagine que oui, il n'y a pas d'accents devant pour éviter un problème d'encodage.

**Comment by elbuki** [comment]
Je comprends, merci!
