### ISSUE TITLE
Trailing slash

### ISSUE THREAD

**Issue by lgmorand** [pgrimaud/ratp-api-rest#2]
Bravo pour le boulot.

je constate néanmoins un petit bug qui pour moi devrait être géré par le parseur de la Web Api, notamment à cause du slash final

https://api-ratp.pierre-grimaud.fr/v3/stations/bus/163**/** => KO
https://api-ratp.pierre-grimaud.fr/v3/stations/bus/163  => OK

C'est pas ultra bloquant mais cela serait plus propre si l'API pouvait ignorer le slash de fermeture comme le fait un site web

Merci

**Comment by pgrimaud** [comment]
Hello @lgmorand 

Actuellement, ce n'est pas vraiment possible à cause de la logique du routing.

___

**Explication :** 

```
GET  /lines/rers
```
Cette ressource va renvoyer, la liste des lignes RERS.

Alors que :

```
GET  /lines/rers/
```
Cette ressource va renvoyer, la ligne (vide) du RER.

___

**Néanmoins, je peux gérer une redirection 301 si un slash est ajouté en bout d'url.**

Exemple :

```
GET  /lines/rers/ => 301 /lines/rers

```

Est-ce que ça t'irait ? Il te suffit juste t'activer l'option "follow location" de ton parseur.
