### ISSUE TITLE
api-ratp.pierre-grimaud.fr/v4/traffic ne march plus

### ISSUE THREAD

**Issue by fufubonheur** [pgrimaud/ratp-api-rest#34]
Bonjour,

D'abord votre API est manique ! Bravo ! 
Je suis en train de faire un projet d'école basé votre API.
Depuis cette après midi, https://api-ratp.pierre-grimaud.fr/v4/traffic ne march plus.
La réponse est 
{
    "result": {
        "code": 500,
        "message": "Internal Server Error"
    },
    "_metadata": {
        "call": "GET /traffic",
        "date": "2019-12-16T23:47:15+01:00",
        "version": 4
    }
}

Veillez trouver le problème, SVP. Merci

**Comment by pgrimaud** [comment]
Hello,

Je viens de corriger le problème : https://github.com/pgrimaud/ratp-api-rest/commit/6951064aceddb69c6e11a1d174af93977fe16689
