### ISSUE TITLE
Destinations API (A/R) for buses seem wrong

### ISSUE THREAD

**Issue by ChadiEM** [pgrimaud/ratp-api-rest#5]
https://api-ratp.pierre-grimaud.fr/v3/destinations/bus/22?_format=json
"Porte de Saint-Cloud" >> A
"Opera" >> "R"

But should be the opposite: A for Opera and R for Porte de Saint-Cloud.

https://api-ratp.pierre-grimaud.fr/v3/schedules/bus/22/ranelagh/A?_format=json
-> Direction Opera :-)

It seems correct for the metro; didn't test the RER and Tram.

**Comment by ChadiEM** [comment]
I didn't run it, but by having a look at the code, it seems like the A/R result is taken directly as provided by RATP. Do you confirm it's a bug on their side?

**Comment by pgrimaud** [comment]
Hi @ChadiEM 

Sorry about the delay. 
Yes, it’s a bug on their side and I can’t fix it. 

I will send them an email about it. 

Thanks for the information :)
