### ISSUE TITLE
Tramway Line 11 being ambiguous when fetching schedules

### ISSUE THREAD

**Issue by FlyingYeti** [pgrimaud/ratp-api-rest#7]
Requesting [https://api-ratp.pierre-grimaud.fr/v3/lines/tramways?_format=json]() gives the line 11 with `"code": "11"` but when trying to fetch schedules [https://api-ratp.pierre-grimaud.fr/v3/schedules/tramways/11/le+bourget/A+R?_format=json]() then `"code": 400, "message": "Ambiguous Line"`

**Comment by pgrimaud** [comment]
Hello @FlyingYeti 

Unfortunately, the line T11 is managed by the SNCF and not by the RATP. So the official RATP API is not working properly. 

Sorry about it.
