### ISSUE TITLE
Bus TVM line code

### ISSUE THREAD

**Issue by FlyingYeti** [pgrimaud/ratp-api-rest#8]
Requesting [https://api-ratp.pierre-grimaud.fr/v3/lines/bus?_format=json]() gives `{"code": "vm", "name": "Bus RATP Tvm", "directions": "Saint-Maur - Creteil RER / la Croix de Berny-RER", "id": "194216"}` but the code is wrong (should be `"code": "tvm"`) as [https://api-ratp.pierre-grimaud.fr/v3/stations/bus/vm?_format=json]() gives `"code": 400, "message": "Ambiguous Line"` but [https://api-ratp.pierre-grimaud.fr/v3/stations/bus/tvm?_format=json]() gives the correct stations list

**Comment by pgrimaud** [comment]
Hi @FlyingYeti,

You can try this resource to retrieve stations of the bus `vm`: 
https://api-ratp.pierre-grimaud.fr/v3/stations/bus/vm?id=194216
