### ISSUE TITLE
HTTP error 500

### ISSUE THREAD

**Issue by Elegary** [pgrimaud/ratp-api-rest#9]
Bonsoir,
J'ai suivi l'installation et j'obtiens une erreur 500. Je pense que c'est peut etre lié au serveur redis. Comment régler ça ?

**Comment by pgrimaud** [comment]
Hello @Elegary,

As-tu testé l'application avec le fichier app_dev.php ?

Par exemple, si tu as installé cette application à l'url suivante : http://api-ratp.localhost, tu peux tester à cette url là : http://api-ratp.localhost/app_dev.php

**Comment by Elegary** [comment]
Ça ne fonctionne pas non plus. Comment faire pour voir d'où vient le problème ? 
EDIT : avec le app_dev.php :
```
(1/1) ClassNotFoundException
Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace?
```
+ logs d'apache
` PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/api-ratp/ratp-api-rest/var/logs/prod.log" could not be opened: failed to open stream: Permission denied in /var/www/api-ratp/ratp-api-rest/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107`
Probleme de permissions.
**UPDATE: Problème résolu --> permissions de var/logs/**

**Comment by pgrimaud** [comment]
Essaie ça :
```
composer install
chmod 777 -R var/logs
chmod 777 -R var/cache
```

**Comment by Elegary** [comment]
Maintenant nouveau problème, après le passage en https on dirait que ça boucle, et quand je vais manuellement en HTTPS, ça me ramène en HTTP classique.

**Comment by pgrimaud** [comment]
Dans le fichier app/config/parameters.yml change la clé *schemes* avec la valeur *https* puis lance la commande bin/cache.

**Comment by Elegary** [comment]
Yes merci c'est parfait ;)
